//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Task7Test.Properties
{
	/// <summary>
	///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
	/// </summary>
	// Этот класс создан автоматически классом StronglyTypedResourceBuilder
	// с помощью такого средства, как ResGen или Visual Studio.
	// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
	// с параметром /str или перестройте свой проект VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task7Test.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Перезаписывает свойство CurrentUICulture текущего потока для всех
		///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap p128
		{
			get
			{
				object obj = ResourceManager.GetObject("p128", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap p256
		{
			get
			{
				object obj = ResourceManager.GetObject("p256", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap p32
		{
			get
			{
				object obj = ResourceManager.GetObject("p32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap p64
		{
			get
			{
				object obj = ResourceManager.GetObject("p64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap png
		{
			get
			{
				object obj = ResourceManager.GetObject("png", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
