//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task2Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Task2 {
            get {
                object obj = ResourceManager.GetObject("Task2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500
        ///491 496 2208
        ///489 497 1661
        ///13 379 1290
        ///274 396 4414
        ///375 491 6690
        ///287 401 3885
        ///479 492 250
        ///58 487 2903
        ///180 464 5466
        ///381 498 2523
        ///18 375 4330
        ///489 491 676
        ///367 473 4738
        ///270 278 7429
        ///65 442 8400
        ///365 497 185
        ///230 407 478
        ///494 496 5981
        ///338 366 6905
        ///51 303 3722
        ///268 419 4505
        ///248 348 9326
        ///72 114 9391
        ///73 447 7634
        ///360 413 3665
        ///37 225 3828
        ///100 383 2153
        ///170 470 3443
        ///247 248 8372
        ///264 430 5575
        ///360 460 5171
        ///215 415 6183
        ///204 392 1102
        ///97 116 7640
        ///133 165 1141
        ///90 321 9865
        ///376 422 3999
        ///20  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test_graph_500 {
            get {
                return ResourceManager.GetString("test_graph_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5435
        ///4114 4356 6382
        ///1103 4224 3514
        ///1626 2876 4201
        ///158 1514 4177
        ///1700 5274 1416
        ///4080 5152 8246
        ///1498 3117 5369
        ///2414 3661 8962
        ///4726 5010 2569
        ///1068 1327 7485
        ///3976 4285 5325
        ///2569 4171 3628
        ///5011 5267 9436
        ///1518 2975 5492
        ///4163 4194 206
        ///4533 5404 8893
        ///2242 3691 5713
        ///4008 4612 243
        ///2833 3647 7706
        ///4031 4499 3190
        ///512 1017 2688
        ///3649 4180 450
        ///4810 5335 3980
        ///4231 5228 1872
        ///4787 5432 391
        ///5367 5413 3884
        ///4758 4782 4358
        ///1997 4691 6053
        ///963 5408 7883
        ///2761 5305 2460
        ///3217 3616 2706
        ///3394 3771 2694
        ///1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test_graph_5435 {
            get {
                return ResourceManager.GetString("test_graph_5435", resourceCulture);
            }
        }
    }
}
